### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by vr-wonny** [SamsungDForum/ffmpeg-bindings#1]
Hello guys. Sorry for issue here, but I am ignored and i need help with smartViewSDK iOS.
In last update (version 3.0) developers missed "@objc". 
Please contact with developers of smartViewSDK and show them this issue:
https://github.com/SamsungDForum/SmartViewSDKDefaultMediaPlayer2.0/issues/11

or this issue on forum: https://forum.developer.samsung.com/t/smartviewsdk-3-0-ios-not-working/13586

 Thank you!

**Comment by GTea3** [comment]
@ankitsharma246  Are you able to help @vr-wonny?
